# Generated by Django 3.0.6 on 2020-05-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200526_1012'),
        ('tournaments', '0002_auto_20200524_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('lose_successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lose_predecessors', to='tournaments.TournamentGame')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.Tournament')),
                ('win_successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_predecessors', to='tournaments.TournamentGame')),
            ],
        ),
    ]
