# Generated by Django 3.0.6 on 2020-05-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentgame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='exclude_users',
            new_name='include_users',
        ),
    ]
