# Generated by Django 3.0.6 on 2020-05-28 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_score'),
        ('tournaments', '0004_auto_20200527_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Submission')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tournaments.Tournament')),
            ],
        ),
    ]
