# Generated by Django 3.0.6 on 2020-05-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsubmission',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournaments.Tournament'),
        ),
    ]
