# Generated by Django 3.0.6 on 2020-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20200528_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
