# Generated by Django 3.0.6 on 2020-06-05 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_time_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
