# Generated by Django 3.0.7 on 2020-06-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200605_0158'),
        ('tournaments', '0008_tournament_game_time_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentSubmission',
            new_name='TournamentPlayer',
        ),
        migrations.RemoveField(
            model_name='tournamentgame',
            name='lose_successor',
        ),
        migrations.RemoveField(
            model_name='tournamentgame',
            name='win_successor',
        ),
    ]
