# Generated by Django 3.0.7 on 2020-06-13 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournament_bye_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='num_rounds',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(75)]),
        ),
    ]
