# Generated by Django 3.0.7 on 2020-06-13 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_num_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.Tournament'),
        ),
    ]
