# Generated by Django 3.0.7 on 2020-06-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200611_2219'),
        ('tournaments', '0013_auto_20200613_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Game'),
        ),
    ]
