# Generated by Django 3.0.7 on 2020-06-13 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20200613_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='played',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(75)]),
        ),
    ]
