# Generated by Django 3.0.7 on 2020-06-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_submission_tournament_win_year'),
        ('tournaments', '0015_tournament_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
