# Generated by Django 3.0.7 on 2020-06-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_submission_is_legacy'),
        ('tournaments', '0016_auto_20200613_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='bye_player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='bye', to='games.Submission'),
        ),
    ]
