# Generated by Django 3.0.7 on 2020-06-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_submission_is_legacy'),
        ('tournaments', '0017_auto_20200618_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='include_users',
            field=models.ManyToManyField(blank=True, to='games.Submission'),
        ),
    ]
