# Generated by Django 3.0.7 on 2020-06-23 22:59

from django.db import migrations, models
import othello.apps.games.validators
import othello.apps.tournaments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_auto_20200618_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_time_limit',
            field=models.IntegerField(default=1, validators=[othello.apps.games.validators.validate_game_time_limit]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_rounds',
            field=models.IntegerField(default=15, validators=[othello.apps.tournaments.validators.validate_tournament_rounds]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
