# Generated by Django 3.0.7 on 2020-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_auto_20200623_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='celery_task_id',
            field=models.CharField(default='', max_length=48),
        ),
    ]
