# Generated by Django 3.0.7 on 2020-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_tournament_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='runoff_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
