# Generated by Django 3.1.7 on 2021-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_auto_20210422_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='cumulative',
            field=models.FloatField(default=0),
        ),
    ]
