# Generated by Django 5.0.7 on 2024-09-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_auto_20220804_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='black_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='white_games',
            field=models.IntegerField(default=0),
        ),
    ]
