# Generated by Django 5.0.7 on 2024-09-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_tournamentplayer_black_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='black_games',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='white_games',
        ),
    ]
