# Generated by Django 3.2.24 on 2025-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_remove_tournamentplayer_black_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pairing_algorithm',
            field=models.CharField(choices=[('random', 'Random'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss'), ('danish', 'Danish')], default='swiss', max_length=20),
        ),
    ]
