# Generated by Django 3.2.24 on 2025-08-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_tournament_pairing_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_robin_matches',
            field=models.IntegerField(default=2, help_text='How many matches to play between two players in a round robin tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pairing_algorithm',
            field=models.CharField(choices=[('random', 'Random'), ('swiss', 'Swiss'), ('danish', 'Danish'), ('round_robin', 'Round Robin')], default='swiss', max_length=20),
        ),
    ]
