# Generated by Django 3.0.7 on 2020-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200612_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
