# Generated by Django 3.2.25 on 2024-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210422_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gauntlet_running',
            field=models.BooleanField(default=False),
        ),
    ]
