# Generated by Django 3.2.25 on 2024-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_is_gauntlet_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_gauntlet_run',
            field=models.DateTimeField(null=True),
        ),
    ]
