# Generated by Django 5.2.10 on 2026-02-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_rating_ratinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=6),
        ),
    ]
