# Generated by Django 5.2.10 on 2026-02-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_ranked_matches',
            field=models.BooleanField(default=True, help_text='Allow any user to request ranked matches against you'),
        ),
        migrations.AddField(
            model_name='user',
            name='accept_unranked_matches',
            field=models.BooleanField(default=True, help_text='Allow any user to request unranked matches against you'),
        ),
    ]
