# Generated by Django 3.2.25 on 2024-07-17 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import othello.apps.games.validators


class Migration(migrations.Migration):

    replaces = [('rating', '0001_initial'), ('rating', '0002_auto_20240525_1335'), ('rating', '0003_auto_20240525_2011'), ('rating', '0004_alter_gauntlet_myside1'), ('rating', '0005_auto_20240526_1510'), ('rating', '0006_alter_gauntlet_myside2'), ('rating', '0007_auto_20240526_1512'), ('rating', '0008_auto_20240526_1514'), ('rating', '0009_auto_20240526_1536'), ('rating', '0010_alter_gauntlet_myside3'), ('rating', '0011_auto_20240527_2119'), ('rating', '0012_gauntlet_pastrating'), ('rating', '0013_gauntlet_celery_task_id'), ('rating', '0014_alter_gauntlet_myside2'), ('rating', '0015_auto_20240528_0833'), ('rating', '0016_alter_gauntlet_myside2'), ('rating', '0017_auto_20240716_1826'), ('rating', '0018_auto_20240716_1826'), ('rating', '0019_auto_20240716_1828'), ('rating', '0020_auto_20240716_1829'), ('rating', '0021_auto_20240716_1830'), ('rating', '0022_auto_20240716_1831'), ('rating', '0023_auto_20240716_1932'), ('rating', '0024_auto_20240716_1934'), ('rating', '0025_auto_20240716_1934')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0032_submission_gauntlet'),
        ('games', '0036_game_is_gauntlet'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_run', models.BooleanField(default=False)),
                ('next_auto_run', models.DateTimeField()),
                ('running', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='g', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Gauntlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('game_time_limit', models.IntegerField(default=5, validators=[othello.apps.games.validators.validate_game_time_limit])),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('terminated', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='gauntletsubmission', to='games.submission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g1', to='games.game')),
                ('game2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g2', to='games.game')),
                ('game3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g3', to='games.game')),
                ('mySide1', models.CharField(default='x', max_length=1)),
                ('mySide2', models.CharField(default='o', max_length=1)),
                ('mySide3', models.CharField(default='o', max_length=1)),
                ('pastRating', models.IntegerField(default=400)),
                ('celery_task_id', models.CharField(default='', max_length=48)),
            ],
        ),
    ]
