# Generated by Django 3.2.25 on 2024-05-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_submission_gauntlet'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gauntlet',
            name='game1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g1', to='games.game'),
        ),
        migrations.AddField(
            model_name='gauntlet',
            name='game2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g2', to='games.game'),
        ),
        migrations.AddField(
            model_name='gauntlet',
            name='game3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g3', to='games.game'),
        ),
    ]
