# Generated by Django 3.2.25 on 2024-05-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20240525_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='gauntlet',
            name='mySide1',
            field=models.CharField(default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='gauntlet',
            name='mySide2',
            field=models.CharField(default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='gauntlet',
            name='mySide3',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
