# Generated by Django 3.2.25 on 2024-05-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20240525_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide1',
            field=models.CharField(default='x', max_length=1),
        ),
    ]
