# Generated by Django 3.2.25 on 2024-05-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20240526_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide2',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
