# Generated by Django 3.2.25 on 2024-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_auto_20240526_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_run', models.BooleanField(default=False)),
                ('next_auto_run', models.DateTimeField(auto_now=True)),
                ('running', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(default='', max_length=48)),
            ],
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide1',
            field=models.CharField(default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide3',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
