# Generated by Django 3.2.25 on 2024-05-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_auto_20240526_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide3',
            field=models.CharField(default='x', max_length=1),
        ),
    ]
