# Generated by Django 3.2.25 on 2024-05-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0011_auto_20240527_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='gauntlet',
            name='pastRating',
            field=models.IntegerField(default=400),
        ),
    ]
