# Generated by Django 3.2.25 on 2024-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_gauntlet_pastrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gauntlet',
            name='celery_task_id',
            field=models.CharField(default='', max_length=48),
        ),
    ]
