# Generated by Django 3.2.24 on 2024-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0015_auto_20240528_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide2',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
