# Generated by Django 3.2.25 on 2024-07-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_game_is_gauntlet'),
        ('rating', '0016_alter_gauntlet_myside2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankedmanager',
            name='celery_task_id',
        ),
        migrations.AddField(
            model_name='rankedmanager',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g', to='games.game'),
        ),
    ]
