# Generated by Django 3.2.25 on 2024-07-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0019_auto_20240716_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankedmanager',
            name='game',
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide2',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
