# Generated by Django 3.2.25 on 2024-07-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0020_auto_20240716_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide1',
            field=models.CharField(default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide2',
            field=models.CharField(default='x', max_length=1),
        ),
    ]
