# Generated by Django 3.2.25 on 2024-07-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_game_is_gauntlet'),
        ('rating', '0021_auto_20240716_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedmanager',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide2',
            field=models.CharField(default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide3',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
