# Generated by Django 3.2.25 on 2024-07-16 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('games', '0036_game_is_gauntlet'),
        ('rating', '0022_auto_20240716_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.AlterField(
            model_name='gauntlet',
            name='mySide3',
            field=models.CharField(default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='rankedmanager',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='g', to='games.game'),
        ),
    ]
