# Generated by Django 3.0.5 on 2020-04-23 23:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import othello.apps.games.models
import othello.apps.games.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(default=5)),
                ('playing', models.BooleanField(default=False)),
                ('forfeit', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('X', 'Black'), ('O', 'White'), ('T', 'Tie')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('submitted_time', models.DateTimeField(auto_now=True)),
                ('code', models.FileField(default=None, storage=othello.apps.games.storage.OverwriteStorage(), upload_to=othello.apps.games.models.save_path)),
                ('usable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('X', 'Black'), ('O', 'White')], max_length=1)),
                ('board', models.CharField(default='', max_length=64)),
                ('move', models.IntegerField(default=-1)),
                ('flipped', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=None)),
                ('possible', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=list, size=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.Game')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('X', 'Black'), ('O', 'White')], max_length=1)),
                ('message', models.CharField(default='', max_length=10240)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GameError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('X', 'Black'), ('O', 'White')], max_length=1)),
                ('error_code', models.IntegerField(default=-1)),
                ('error_msg', models.CharField(default='', max_length=10240)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='games.Submission'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='games.Submission'),
        ),
    ]
