# Generated by Django 3.0.6 on 2020-05-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameerror',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='gamelog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='move',
            managers=[
            ],
        ),
    ]
