# Generated by Django 3.0.5 on 2020-04-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='board',
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.CharField(default='...........................ox......xo...........................', max_length=64),
        ),
    ]
