# Generated by Django 3.0.6 on 2020-05-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200515_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='flipped',
        ),
    ]
