# Generated by Django 3.0.5 on 2020-04-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200423_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.AddField(
            model_name='move',
            name='board',
            field=models.CharField(default='', max_length=64),
        ),
    ]
