# Generated by Django 3.0.6 on 2020-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_move_flipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
