# Generated by Django 3.0.5 on 2020-04-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200405_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(default=5)),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='games.Submission')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='games.Submission')),
            ],
        ),
    ]
