# Generated by Django 3.0.5 on 2020-04-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_playing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('black', 'white', 'time_limit')},
        ),
    ]
