# Generated by Django 3.0.6 on 2020-05-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200522_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='usable',
        ),
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('x', 'Black'), ('o', 'White'), ('T', 'Tie')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='gameerror',
            name='player',
            field=models.CharField(choices=[('x', 'Black'), ('o', 'White')], max_length=1),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='player',
            field=models.CharField(choices=[('x', 'Black'), ('o', 'White')], max_length=1),
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.CharField(choices=[('x', 'Black'), ('o', 'White')], max_length=1),
        ),
    ]
