# Generated by Django 3.0.6 on 2020-05-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200522_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='black', to='games.Submission'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='white', to='games.Submission'),
        ),
    ]
