# Generated by Django 3.0.6 on 2020-05-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200526_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('x', 'black'), ('o', 'white'), ('T', 'Tie')], default='', max_length=1),
        ),
    ]
