# Generated by Django 3.0.6 on 2020-05-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_submission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
