# Generated by Django 3.0.6 on 2020-05-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('x', 'black'), ('o', 'white'), ('T', 'Tie')], default='Tie', max_length=1),
        ),
    ]
