# Generated by Django 3.0.6 on 2020-06-05 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_limit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)]),
        ),
    ]
