# Generated by Django 3.0.7 on 2020-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200611_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tournament_win_year',
            field=models.IntegerField(default=-1),
        ),
    ]
