# Generated by Django 3.0.7 on 2020-06-18 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_submission_tournament_win_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ping',
        ),
        migrations.AddField(
            model_name='game',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
