# Generated by Django 3.0.7 on 2020-06-18 02:53

from django.db import migrations


def create_yourself_player(apps, schema_editor):
    Submission = apps.get_model("games", "Submission")
    User = apps.get_model("authentication", "User")
    yourself_user = User.objects.create(
        username="Yourself",
        is_teacher=False,
        is_student=False,
        is_superuser=False,
        is_staff=False
    )
    Submission.objects.create(
        user=yourself_user
    )


def delete_yourself_player(apps, schema_editor):
    Submission = apps.get_model("games", "Submission")
    User = apps.get_model("authentication", "User")
    try:
        yourself_user = User.objects.get(username="Yourself")
    except User.DoesNotExist:
        return
    Submission.objects.filter(user=yourself_user).delete()
    yourself_user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200617_2051'),
        ('authentication', '0005_auto_20200612_2148')
    ]

    operations = [
        migrations.RunPython(create_yourself_player, reverse_code=delete_yourself_player)
    ]
