# Generated by Django 3.0.7 on 2020-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20200617_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
