# Generated by Django 3.0.5 on 2020-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20200419_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='game',
            name='playing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
    ]
