# Generated by Django 3.0.7 on 2020-06-23 22:59

from django.db import migrations, models
import othello.apps.games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20200623_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_limit',
            field=models.IntegerField(default=5, validators=[othello.apps.games.validators.validate_game_time_limit]),
        ),
    ]
