# Generated by Django 3.0.7 on 2020-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20201026_0300'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('name__isnull', False), _connector='OR'), name='user_or_name'),
        ),
    ]
