# Generated by Django 3.0.5 on 2020-04-21 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20200420_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='games.Submission'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.CharField(choices=[('X', 'Black'), ('O', 'White')], max_length=1),
        ),
    ]
