# Generated by Django 3.0.7 on 2020-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20201026_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='runoff',
            field=models.BooleanField(default=False),
        ),
    ]
