# Generated by Django 3.0.5 on 2020-04-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20200421_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='forfeit',
            field=models.BooleanField(default=False),
        ),
    ]
