# Generated by Django 3.2.14 on 2022-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20210423_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
