# Generated by Django 3.2.25 on 2024-07-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('games', '0031_auto_20240523_1555'), ('games', '0032_submission_gauntlet'), ('games', '0033_game_is_ranked'), ('games', '0034_auto_20240525_2248'), ('games', '0035_auto_20240526_1514'), ('games', '0036_game_is_gauntlet')]

    dependencies = [
        ('games', '0030_auto_20220804_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rating',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='submission',
            name='gauntlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='ratingDelta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='blackRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='whiteRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_gauntlet',
            field=models.BooleanField(default=False),
        ),
    ]
