# Generated by Django 3.2.25 on 2024-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20240523_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='gauntlet',
            field=models.BooleanField(default=False),
        ),
    ]
