# Generated by Django 5.2.10 on 2026-02-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_match_game_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'get_latest_by': 'created_at'},
        ),
    ]
