# Generated by Django 3.2.25 on 2024-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_submission_gauntlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
    ]
