# Generated by Django 5.2.10 on 2026-02-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_alter_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='games.submission'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='games.submission'),
        ),
    ]
