# Generated by Django 3.0.5 on 2020-04-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_gameerror_gamelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('X', 'Black'), ('O', 'White'), ('T', 'Tie')], default='', max_length=1),
        ),
    ]
