# Generated by Django 5.2.10 on 2026-02-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_match_is_tie_match_loser_match_player1_wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_ranked',
            field=models.BooleanField(default=True),
        ),
    ]
