# Generated by Django 3.2.25 on 2024-05-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_game_is_ranked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='deviation',
        ),
        migrations.AddField(
            model_name='game',
            name='ratingDelta',
            field=models.IntegerField(default=0),
        ),
    ]
