# Generated by Django 3.2.25 on 2024-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_auto_20240525_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='blackRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='whiteRating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
