# Generated by Django 5.2.10 on 2026-02-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_match_is_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_scrimmage',
            field=models.BooleanField(default=False),
        ),
    ]
