# Generated by Django 3.2.25 on 2024-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_auto_20240526_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_gauntlet',
            field=models.BooleanField(default=False),
        ),
    ]
