# Generated by Django 5.2.10 on 2026-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_game_is_scrimmage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_rating_delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_rating_delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
