# Generated by Django 5.2.10 on 2026-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_match_player1_rating_delta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1_rating_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_rating_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
