# Generated by Django 3.0.5 on 2020-04-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200405_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='time',
            new_name='submitted_time',
        ),
    ]
