# Generated by Django 3.0.5 on 2020-04-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_submission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(default='2020-04-15 15:43:32', max_length=500),
        ),
    ]
