# Generated by Django 3.0.5 on 2020-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200415_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
