# Generated by Django 3.0.5 on 2020-04-15 22:04

from django.db import migrations, models
import othello.apps.games.models
import othello.apps.games.storage


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200415_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.FileField(default=None, storage=othello.apps.games.storage.OverwriteStorage(), upload_to=othello.apps.games.models.save_path),
        ),
    ]
