# Generated by Django 3.0.5 on 2020-04-17 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200415_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('B', 'Black'), ('W', 'White')], max_length=1)),
                ('board', models.CharField(default='', max_length=64)),
                ('move', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(64), django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.Game')),
            ],
        ),
    ]
