# Generated by Django 3.0.5 on 2020-04-17 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20200417_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxLengthValidator(64), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
