# Generated by Django 3.0.5 on 2020-04-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20200417_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(default='', max_length=10240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteGameLog',
            fields=[
                ('gamelog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameLog')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_logs', to='games.Game')),
            ],
            bases=('games.gamelog',),
        ),
        migrations.CreateModel(
            name='BlackGameLog',
            fields=[
                ('gamelog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameLog')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_logs', to='games.Game')),
            ],
            bases=('games.gamelog',),
        ),
    ]
