# Generated by Django 3.0.5 on 2020-04-17 07:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_blackgamelog_gamelog_whitegamelog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blackgamelog',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gamelog',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='whitegamelog',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
