# Generated by Django 3.0.5 on 2020-04-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200417_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
