# Generated by Django 3.0.5 on 2020-04-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_blackgameerror_gameerror_whitegameerror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameerror',
            old_name='error',
            new_name='error_code',
        ),
        migrations.AddField(
            model_name='gameerror',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
