# Generated by Django 3.0.5 on 2020-04-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20200419_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.RemoveField(
            model_name='move',
            name='valid',
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.CharField(choices=[('1', 'Black'), ('0', 'White')], max_length=1),
        ),
    ]
