# Generated by Django 3.0.5 on 2020-04-19 06:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20200419_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='possible',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.CharField(choices=[(1, 'Black'), (0, 'White')], max_length=1),
        ),
    ]
