# Generated by Django 3.0.5 on 2020-04-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20200421_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('X', 'Black'), ('O', 'White')], default=None, max_length=1),
        ),
    ]
