# Generated by Django 3.0.5 on 2020-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_game_forfeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.IntegerField(default=-1),
        ),
    ]
