# Generated by Django 3.0.5 on 2020-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20200421_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('X', 'Black'), ('O', 'White')], default='', max_length=1),
        ),
    ]
