# Generated by Django 3.0.5 on 2020-04-21 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20200421_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('X', 'Black'), ('O', 'White')], max_length=1)),
                ('message', models.CharField(default='', max_length=10240)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GameError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('X', 'Black'), ('O', 'White')], max_length=1)),
                ('error_code', models.IntegerField(default=-1)),
                ('error_msg', models.CharField(default='', max_length=10240)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
