name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

.anchors:
  python_versions: &python_versions
    - 3.8
    - 3.9

  repo_setup: &repo_setup
    name: Set up repo
    uses: actions/checkout@v2

  python_setup: &python_setup
    name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v5
    with:
      python-version: ${{ matrix.python-version }}
      cache: pipenv

  install_deps: &install_deps
    name: Install dependencies
    run: |
      set -e
      pip install pipenv
      pipenv install --dev --deploy

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: *python_versions

    steps:
      - *repo_setup
      - *python_setup
      - *install_deps

      - name: Check formatting with format.sh
        run: pipenv run ./scripts/format.sh && test -z "$(git status --porcelain=v1 .)"

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: *python_versions

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: othello
          POSTGRES_DB: othello
          POSTGRES_PASSWORD: pwd
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 6s --health-timeout 5s --health-retries 9

    steps:
      - *repo_setup
      - *python_setup
      - *install_deps

      - name: Copy secret.py
        run: cp othello/settings/secret.sample.py othello/settings/secret.py

      - name: Migrate database
        run: pipenv run python3 manage.py migrate

      - name: Collect static files
        run: pipenv run python3 manage.py collectstatic --noinput -v 0

      - name: Run tests
        run: pipenv run coverage run ./manage.py test

      - name: Report coverage to Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true

  finish_success:
    needs:
      - format
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Tell Coveralls that parallel jobs have finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
